import fs from "fs";
import path from "path";
import type { ApiFont, GoldenFixture, GoldenInputs } from "./golden";
import { fixture, uiReachableFixtures } from "./golden";
import { IS_LIVE, TARGET } from "./target";

/**
 * Where the expected CSS and design tokens come from — the one thing that genuinely
 * differs between the two targets.
 *
 * **Hermetic** serves a fixed six-family catalogue, so the expectation is the bytes
 * committed in `core/src/__tests__/fixtures/golden.json`. That is the strongest assertion
 * available: it pins the app to a value a human reviewed, and it fails if `core` drifts.
 *
 * **Live** cannot use those fixtures. Four of the six fixture families are synthetic and do
 * not exist on Google Fonts, and of the two that do, `Roboto` has since gained weights 200,
 * 600 and 800 — which changes `weightSteps` and therefore every generated byte. Measured
 * against the real catalogue, exactly one fixture still reproduces, and only by luck.
 *
 * So live mode derives its expectation at runtime instead:
 *
 * 1. Fetch the catalogue the app is about to fetch.
 * 2. Pick one family per *shape* (see SHAPES) — never by name.
 * 3. Compute the answer with `core`, the same functions the app composes through its stores.
 *
 * Adding a font to Google's catalogue therefore cannot fail this suite: the worst it can do
 * is change which family a shape resolves to, and the expectation moves with it. A family
 * being *redefined* mid-run is the one remaining hazard, and `assertCatalogueAgrees` below
 * turns that into a legible failure rather than a byte diff.
 *
 * The trade-off, stated plainly: the live oracle shares an implementation with the thing it
 * measures, so it cannot catch a bug inside `core`. It is not meant to — `core`'s own golden
 * test and the hermetic run both do. What live mode uniquely proves is that the *deployed*
 * app, the real API, real auth and real CORS all still agree with `core`.
 */

/**
 * `core` is `"type": "module"` and these files transpile to CommonJS, so it has to be
 * reached with a dynamic `import()`. By relative path into `dist/` rather than through the
 * package name, mirroring how support/golden.ts already reads core's fixtures off disk —
 * and `e2e/turbo.json`'s `dependsOn: ["core#build"]` is what guarantees `dist` is there.
 */
type Core = typeof import("../../core/dist/index.js");

let corePromise: Promise<Core> | null = null;

export const loadCore = (): Promise<Core> => {
	corePromise ??= import("../../core/dist/index.js");
	return corePromise;
};

/** One drivable test case, whichever target produced it. */
export interface Case {
	label: string;
	inputs: GoldenInputs;
	expected: { cssCode: string; designTokens: string };
	/**
	 * The variant table behind `expected`, for the preview spec, which asserts computed
	 * pixel values rather than bytes.
	 */
	typescale: GoldenFixture["typescale"];
	/** The weights the app should be offering for this family. Empty when unknown. */
	availableWeights: number[];
}

// ── live: choosing subjects by shape ─────────────────────────────────────────────────

interface Shape {
	name: string;
	/** Why this shape is worth a case at all — surfaced when no family matches. */
	covers: string;
	matches(weights: number[], font: ApiFont): boolean;
	/** The heading range to drive, taken from the family's own weights so no clamp is needed. */
	range(weights: number[]): { initial: number; final: number };
}

const SHAPES: Shape[] = [
	{
		name: "multi-weight-ascending",
		covers: "the ordinary case: a range spanning several weights, title-1 heaviest",
		matches: (weights) => weights.length >= 3 && weights.includes(400),
		// Widest range the family allows, ascending — `weightStepsFor` reverses it.
		range: (weights) => ({ initial: weights[0], final: weights[weights.length - 1] })
	},
	{
		name: "multi-weight-descending",
		covers: "the reversed range, which `weightStepsFor` must not reverse",
		matches: (weights) => weights.length >= 3 && weights.includes(400),
		range: (weights) => ({ initial: weights[weights.length - 1], final: weights[0] })
	},
	{
		name: "single-weight",
		covers: "clampHeadingWeights pinning both ends, and the range control being disabled",
		matches: (weights) => weights.length === 1,
		range: (weights) => ({ initial: weights[0], final: weights[0] })
	},
	{
		name: "no-regular",
		covers: "a family with no 400, where the fallback in clampHeadingWeights is what runs",
		matches: (weights) => weights.length >= 2 && !weights.includes(400),
		range: (weights) => ({
			initial: weights[weights.length - 1],
			final: weights[weights.length - 1]
		})
	}
];

/**
 * The numeric half of the inputs — base size, ratios, breakpoint, letter spacing. Borrowed
 * from a fixture because they carry no dependency on the catalogue at all: the same numbers
 * mean the same thing whatever family is selected.
 */
const NUMERIC_INPUTS = (() => {
	const { baseSize, baseUnit, desktopRatio, mobileRatio, letterSpacingRatio, breakpoint } =
		fixture("defaults-red-hat-text").inputs;

	return { baseSize, baseUnit, desktopRatio, mobileRatio, letterSpacingRatio, breakpoint };
})();

export interface LiveCatalogue {
	items: ApiFont[];
	fetchedAt: number;
}

let cataloguePromise: Promise<LiveCatalogue> | null = null;

export const fetchLiveCatalogue = async (force = false): Promise<LiveCatalogue> => {
	if (force) cataloguePromise = null;

	cataloguePromise ??= (async () => {
		const url = `${TARGET.apiUrl}/api/fonts`;
		const response = await fetch(url);

		if (!response.ok) {
			throw new Error(`GET ${url} answered ${response.status} ${response.statusText}`);
		}

		const body = (await response.json()) as { items?: ApiFont[] };

		if (!Array.isArray(body.items) || body.items.length === 0) {
			throw new Error(`GET ${url} answered no font items — the KV snapshot may be empty`);
		}

		return { items: body.items, fetchedAt: Date.now() };
	})();

	return cataloguePromise;
};

/**
 * Deterministic on purpose: candidates are sorted by family name and the first is taken.
 * Two runs an hour apart pick the same family, so a failure is reproducible — and when a
 * newly added font does sort ahead of the incumbent, the expectation is recomputed for it,
 * which is exactly the flexibility this design is for.
 */
/**
 * AutoComplete.svelte's own id scheme, which is how the page object clicks an option:
 * `option.toLowerCase().replaceAll(" ", "-")`. No family in today's 1951 produces anything
 * but a bare CSS identifier, but the catalogue grows without asking us — and a family whose
 * id needs escaping would make `li#…` an invalid selector, failing as a cryptic locator
 * error rather than a skipped subject.
 */
export const optionId = (family: string): string => family.toLowerCase().replaceAll(" ", "-");
const hasUsableOptionId = (family: string): boolean => /^[a-z][a-z0-9-]*$/.test(optionId(family));

const pickFamily = async (shape: Shape, items: ApiFont[]): Promise<ApiFont | null> => {
	const { availableWeightsFor } = await loadCore();

	const candidates = items
		.filter((font) => {
			const weights = availableWeightsFor(font);
			// A family whose weights core cannot read at all is no use to any shape: the
			// generated `@import` would carry an empty `wght@` list.
			return weights.length > 0 && hasUsableOptionId(font.family) && shape.matches(weights, font);
		})
		.sort((a, b) => a.family.localeCompare(b.family));

	return candidates[0] ?? null;
};

const liveCase = async (shape: Shape, font: ApiFont): Promise<Case> => {
	const { availableWeightsFor, computeTypescale, generateCss, generateTokens } = await loadCore();

	const availableWeights = availableWeightsFor(font);
	const { initial, final } = shape.range(availableWeights);

	const inputs: GoldenInputs = {
		...NUMERIC_INPUTS,
		fontName: font.family,
		useUppercaseForTitles: false,
		useItalicsForTitles: false,
		headingsInitialWeight: initial,
		headingsFinalWeight: final
	};

	// The same composition the client performs through its stores — `computeTypescale` is
	// core's own single-call equivalent, and the golden fixtures are what prove the two
	// agree, so using it here does not weaken the comparison.
	const computed = computeTypescale(inputs, availableWeights);

	return {
		label: `${shape.name} (${font.family})`,
		inputs,
		typescale: computed.typescale as GoldenFixture["typescale"],
		availableWeights,
		expected: {
			cssCode: generateCss(computed.typescale, inputs.breakpoint, font, computed.weightSteps),
			designTokens: generateTokens(computed.typescale, inputs.breakpoint, font)
		}
	};
};

// ── the mode-aware entry point ───────────────────────────────────────────────────────

const hermeticCases = (): Case[] =>
	uiReachableFixtures.map((golden) => ({
		label: golden.label,
		inputs: golden.inputs,
		typescale: golden.typescale,
		availableWeights: golden.availableWeights,
		expected: { cssCode: golden.cssCode, designTokens: golden.designTokens }
	}));

/**
 * A shape that found no family in the live catalogue. Reported as a skip naming the shape
 * rather than silently dropped, so the run's coverage is legible from its own output.
 */
export interface MissingShape {
	label: string;
	reason: string;
}

export interface ResolvedSubjects {
	mode: "hermetic" | "live";
	/** Only meaningful live: how many families the catalogue held when this was resolved. */
	catalogueSize: number;
	cases: Case[];
	missing: MissingShape[];
}

/**
 * Resolved once per run, by `globalSetup`, and written here for the workers to read.
 *
 * Two reasons it cannot simply happen in each spec file. Playwright collects tests
 * synchronously and these files transpile to CommonJS, so there is no top-level `await` to
 * fetch a catalogue with. And more importantly, resolving once means every worker compares
 * against the *same* snapshot — if each fetched its own, a run straddling the daily KV
 * rewrite could have two workers disagreeing about what the right answer is.
 */
const CACHE = path.resolve(__dirname, "../playwright/.cache/subjects.json");

export const resolveSubjects = async (): Promise<ResolvedSubjects> => {
	if (!IS_LIVE) {
		return { mode: "hermetic", catalogueSize: 0, cases: hermeticCases(), missing: [] };
	}

	const { items } = await fetchLiveCatalogue();
	const cases: Case[] = [];
	const missing: MissingShape[] = [];

	for (const shape of SHAPES) {
		const font = await pickFamily(shape, items);

		if (!font) {
			missing.push({
				label: shape.name,
				reason: `no family in the live catalogue (${items.length} of them) has this shape, so ${shape.covers} is not covered here`
			});
			continue;
		}

		cases.push(await liveCase(shape, font));
	}

	return { mode: "live", catalogueSize: items.length, cases, missing };
};

export const writeSubjects = async (resolved: ResolvedSubjects): Promise<void> => {
	await fs.promises.mkdir(path.dirname(CACHE), { recursive: true });
	await fs.promises.writeFile(CACHE, JSON.stringify(resolved), "utf8");
};

/** The synchronous read the spec files use at collection time. */
export const loadSubjects = (): ResolvedSubjects => {
	if (!fs.existsSync(CACHE)) {
		throw new Error(
			`No resolved subjects at ${CACHE}. They are written by globalSetup — run through \`playwright test\`, not by importing a spec directly.`
		);
	}

	return JSON.parse(fs.readFileSync(CACHE, "utf8")) as ResolvedSubjects;
};

/**
 * Guards the one hazard the runtime oracle still has.
 *
 * The suite's catalogue fetch and the browser's are two separate requests, and the Worker
 * rewrites the KV snapshot on a daily cron — so an hourly run can straddle the rewrite and
 * end up comparing an expectation built from yesterday's catalogue against an app holding
 * today's. Rather than let that surface as an inscrutable byte diff, compare the weights the
 * app itself reports (its `availableWeights`, which is what the heading-range control is
 * populated from) against the ones the expectation was built on.
 *
 * Returns the mismatch as a message, or null when they agree.
 */
export const catalogueDisagreement = (
	expected: readonly number[],
	reportedByApp: readonly number[]
): string | null => {
	const a = [...expected].join(",");
	const b = [...reportedByApp].join(",");

	if (a === b) return null;

	return [
		"The catalogue the app received is not the one this expectation was built from.",
		`  expectation built on: [${a}]`,
		`  app is offering:      [${b}]`,
		"Almost certainly the daily /api/fonts snapshot rotated mid-run, or this family was",
		"redefined upstream. Re-run; if it persists, the family really did change."
	].join("\n");
};
