// One-off Atlas -> D1 export. Reads every document from the Mongo `Typescale`
// collection and writes two files next to this script:
//
//   atlas-export.json  — raw documents, kept as an audit trail / re-run input
//   atlas-import.sql   — INSERT statements to feed `wrangler d1 execute --file`
//
// Run with the same DB_STRING the Worker used:
//   node --env-file=server/.dev.vars server/scripts/export-atlas.mjs
//
// Safe to re-run: the SQL uses INSERT OR REPLACE, and `id` keeps the original
// ObjectId hex string so links the client already stored keep resolving.

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { MongoClient } from "mongodb";

const HERE = dirname(fileURLToPath(import.meta.url));

// Must match the column order in migrations/0001_create_typescales.sql.
const BASE_FIELDS = [
	"breakpoint",
	"fontName",
	"baseUnit",
	"baseSize",
	"desktopRatio",
	"mobileRatio",
	"letterSpacingRatio",
	"useUppercaseForTitles",
	"useItalicsForTitles",
	"headingsInitialWeight",
	"headingsFinalWeight"
];

const INTEGER_BASE_FIELDS = new Set(["breakpoint", "headingsInitialWeight", "headingsFinalWeight"]);
const BOOLEAN_BASE_FIELDS = new Set(["useUppercaseForTitles", "useItalicsForTitles"]);
const TEXT_BASE_FIELDS = new Set(["fontName"]);

function quote(value) {
	return `'${String(value).replace(/'/g, "''")}'`;
}

// SQLite has no boolean type; D1 stores them as 0/1 integers.
function sqlLiteral(value) {
	if (value === null || value === undefined) return "NULL";
	if (typeof value === "boolean") return value ? "1" : "0";
	if (typeof value === "number") return Number.isFinite(value) ? String(value) : "NULL";
	return quote(value);
}

// Mongo held these as strings in some older documents; coerce so the REAL and
// INTEGER columns get real numbers rather than numeric-looking text.
function coerceBaseValue(field, value) {
	if (BOOLEAN_BASE_FIELDS.has(field)) return value === true || value === "true" || value === 1;
	if (TEXT_BASE_FIELDS.has(field)) return typeof value === "string" && value ? value : null;

	const asNumber = typeof value === "string" ? Number(value) : value;
	if (typeof asNumber !== "number" || !Number.isFinite(asNumber)) return null;

	return INTEGER_BASE_FIELDS.has(field) ? Math.round(asNumber) : asNumber;
}

function toIso(value) {
	if (value instanceof Date) return value.toISOString();
	if (typeof value === "string" && !Number.isNaN(Date.parse(value))) {
		return new Date(value).toISOString();
	}
	return new Date(0).toISOString();
}

const uri = process.env.DB_STRING;
if (!uri) {
	console.error("DB_STRING is not set. Run with: node --env-file=server/.dev.vars <this file>");
	process.exit(1);
}

const client = new MongoClient(uri, { serverSelectionTimeoutMS: 10000 });

try {
	await client.connect();
	const collection = client.db().collection(process.env.DB_COLLECTION || "Typescale");
	const docs = await collection.find({}).toArray();

	console.log(`Read ${docs.length} document(s) from Mongo.`);

	writeFileSync(join(HERE, "atlas-export.json"), JSON.stringify(docs, null, 2) + "\n");

	const columns = [
		"id",
		"authorId",
		"name",
		...BASE_FIELDS,
		"overrides",
		"createdAt",
		"lastModifiedAt"
	];
	const problems = [];
	const rows = docs.map((doc) => {
		const base = doc.base || {};
		const values = [
			sqlLiteral(doc._id.toHexString()),
			sqlLiteral(doc.authorId ?? "unknown"),
			sqlLiteral(doc.name ?? "Untitled")
		];

		for (const field of BASE_FIELDS) {
			const coerced = coerceBaseValue(field, base[field]);
			if (coerced === null) problems.push(`${doc._id.toHexString()} is missing base.${field}`);
			values.push(sqlLiteral(coerced));
		}

		values.push(
			doc.overrides === null || doc.overrides === undefined
				? "NULL"
				: quote(JSON.stringify(doc.overrides))
		);
		values.push(sqlLiteral(toIso(doc.createdAt)));
		values.push(sqlLiteral(toIso(doc.lastModifiedAt)));

		return `INSERT OR REPLACE INTO typescales (${columns.join(", ")}) VALUES (${values.join(
			", "
		)});`;
	});

	const sql = [
		"-- Generated by scripts/export-atlas.mjs. Do not edit by hand.",
		`-- ${docs.length} typescale(s) exported from MongoDB Atlas.`,
		"",
		...rows,
		""
	].join("\n");

	writeFileSync(join(HERE, "atlas-import.sql"), sql);

	if (problems.length) {
		console.warn(`\n${problems.length} field(s) came back empty and will import as NULL:`);
		for (const problem of problems) console.warn(`  - ${problem}`);
	}
	console.log("\nWrote scripts/atlas-export.json and scripts/atlas-import.sql");
} finally {
	await client.close().catch(() => {});
}
