// Mirrors what GET /typescales/{default,saved} returns. This used to be the
// `Typescale` type generated by Prisma from the Mongo schema; the API now reads
// from D1 (server/migrations/0001_create_typescales.sql) and re-nests the row's
// columns into `base`, so the shape on the wire is unchanged.

export interface TypescaleBase {
	breakpoint: number;
	fontName: string;
	baseUnit: number;
	baseSize: number;
	desktopRatio: number;
	mobileRatio: number;
	letterSpacingRatio: number;
	useUppercaseForTitles: boolean;
	useItalicsForTitles: boolean;
	headingsInitialWeight: number;
	headingsFinalWeight: number;
}

export interface Typescale {
	id: string;
	authorId: string;
	name: string;
	base: TypescaleBase;
	// Reserved by the API and always null today; nothing in the client reads it.
	overrides: unknown | null;
	// ISO-8601 strings, as JSON has no date type.
	createdAt: string;
	lastModifiedAt: string;
}
